name: Build and push docker image to ECR
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ap-south-1
        role-to-assume: ${{secrets.OIDC_TOKEN_GITHUB}}
        
    - name: test aws crede
      run: aws sts get-caller-identity

      
